# Generated by Django 4.1.7 on 2023-03-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateTimeField(null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=100)),
                ('check_price', models.IntegerField()),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarOrder.appointment')),
            ],
        ),
    ]
