# Generated by Django 4.1.7 on 2023-06-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_car_sold_to_alter_cargallery_car'),
        ('CarOrder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_appointment', to='Cars.car'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_visit', to='CarOrder.appointment'),
        ),
    ]
