# Generated by Django 4.1.7 on 2023-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
