# Generated by Django 4.1.7 on 2023-06-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cars', '0003_alter_car_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_buyer', related_query_name='car_buyer_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargallery',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='Cars.car'),
        ),
    ]
