# Generated by Django 4.1.7 on 2023-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_car_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gears',
            field=models.CharField(choices=[('دستی', 'دستی'), ('اتومات', 'اتومات')], default='دستی', max_length=6),
        ),
    ]
