# Generated by Django 4.1.7 on 2023-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_car_gears'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargallery',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
