# Generated by Django 4.1.7 on 2023-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_cargallery_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargallery',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
