# Generated by Django 3.2.20 on 2023-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0009_remove_cargallery_url_alter_car_fuel_alter_car_gears_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gears',
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='usage',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
