# Generated by Django 3.2.20 on 2023-08-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0015_auto_20230804_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='company',
            new_name='brand',
        ),
    ]
