# Generated by Django 3.2.20 on 2023-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0016_rename_company_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gears',
            new_name='transmission',
        ),
    ]
