# Generated by Django 3.2.20 on 2023-08-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0018_carview'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
